from __future__ import annotations


LANGUAGE_OPTIONS = [
    ("English", "en"),
    ("한국어", "ko"),
]


TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "settings_window_title": "Music Skin Overlay Settings",
        "settings_title": "Music Skin Overlay",
        "settings_subtitle": "Tune the source and compact now-playing display.",
        "tab_basic": "Basic",
        "tab_advanced": "Advanced",
        "language": "Language",
        "preferred_source": "Preferred source",
        "display_mode": "Display mode",
        "show_duration": "Show duration",
        "background_opacity": "Background opacity",
        "thumbnail": "Thumbnail",
        "title": "Title",
        "details": "Details",
        "time": "Time",
        "progress": "Progress",
        "show_thumbnail": "Show thumbnail",
        "show_title": "Show title",
        "show_details": "Show artist and album",
        "show_time": "Show time",
        "show_progress": "Show progress bar",
        "overlay_text_width": "Overlay text width",
        "text_width_hint": "Controls where long titles become ...",
        "font": "Font",
        "title_size": "Title size",
        "detail_size": "Detail size",
        "meta_size": "Meta size",
        "title_color": "Title color",
        "detail_color": "Detail color",
        "meta_color": "Meta color",
        "accent_color": "Accent color",
        "reset_position": "Reset Position",
        "close": "Close",
        "source_auto": "Auto",
        "source_spotify": "Spotify",
        "source_chrome": "Chrome",
        "source_edge": "Edge",
        "source_current": "Current Windows session",
        "mode_always": "Always visible",
        "mode_on_change": "Show on media change",
        "refresh_now": "Refresh now",
        "media_source": "Media source",
        "settings": "Settings...",
        "quit": "Quit",
        "now": "Now",
        "no_media": "No media playing",
        "show_overlay": "Show overlay",
        "hide_overlay": "Hide overlay",
        "prefer_source": "Prefer source",
    },
    "ko": {
        "settings_window_title": "Music Skin Overlay 설정",
        "settings_title": "Music Skin Overlay",
        "settings_subtitle": "재생 소스와 오버레이 표시 방식을 조정합니다.",
        "tab_basic": "기본",
        "tab_advanced": "고급",
        "language": "언어",
        "preferred_source": "우선 소스",
        "display_mode": "표시 모드",
        "show_duration": "표시 시간",
        "background_opacity": "배경 투명도",
        "thumbnail": "썸네일",
        "title": "제목",
        "details": "상세 정보",
        "time": "시간",
        "progress": "재생바",
        "show_thumbnail": "썸네일 표시",
        "show_title": "제목 표시",
        "show_details": "아티스트/앨범 표시",
        "show_time": "시간 표시",
        "show_progress": "재생바 표시",
        "overlay_text_width": "오버레이 텍스트 폭",
        "text_width_hint": "긴 제목이 어디부터 ... 처리될지 조정합니다.",
        "font": "폰트",
        "title_size": "제목 크기",
        "detail_size": "상세 크기",
        "meta_size": "메타 크기",
        "title_color": "제목 색상",
        "detail_color": "상세 색상",
        "meta_color": "메타 색상",
        "accent_color": "강조 색상",
        "reset_position": "위치 초기화",
        "close": "닫기",
        "source_auto": "자동",
        "source_spotify": "Spotify",
        "source_chrome": "Chrome",
        "source_edge": "Edge",
        "source_current": "현재 Windows 세션",
        "mode_always": "항상 표시",
        "mode_on_change": "미디어 변경 시 표시",
        "refresh_now": "지금 새로고침",
        "media_source": "미디어 소스",
        "settings": "설정...",
        "quit": "종료",
        "now": "현재",
        "no_media": "재생 중인 미디어 없음",
        "show_overlay": "오버레이 표시",
        "hide_overlay": "오버레이 숨기기",
        "prefer_source": "우선 소스",
    },
}


def normalize_language(language: str | None) -> str:
    if language in TRANSLATIONS:
        return str(language)
    return "en"


def translate(key: str, language: str | None) -> str:
    language = normalize_language(language)
    return TRANSLATIONS[language].get(key) or TRANSLATIONS["en"].get(key, key)
